---
server:
  port: 8080
spring:
  application:
    name: kafka-spring-cloud-streams
  kafka:
    bootstrap-servers: http://localhost:9092
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
#      client-id: patient-consumer-id-${random.uuid}

  # datasource & h2 config
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ""
  h2:
    console:
      path: "/h2-console"
      settings:
        web-allow-others: false

  # spring-cloud-streams kafka config
  cloud:
    function:
      definition: patientConsumer;patientSupplier;patientPatientFunction
    stream:
      kafka:
        binder:
          brokers: "localhost:9092"
          replication-factor: 1
        streams:
          binder:
            configuration:
              commit:
                interval:
                  ms: 1000
      poller:
        fixed-delay: 100

      # bindings consumer
      bindings:
        patientConsumer-in-0:
          destination: topicRV
          group: topicRVGroup

      # bindings supplier
        patientSupplier-out-0:
          destination: topicRVSupplier
          group: topicRVSupplierGroup

      # bindings function (consumer & supplier)
        patientPatientFunction-in-0:
          destination: topicRVSupplier
          group: topicRVSupplierGroup
        patientPatientFunction-out-0:
          destination: topicRVFunction
          group: topicRVFunctionGroup